### ISSUE TITLE
Edit legend

### ISSUE THREAD

**Issue by karmstro77** [Esri/map-journal-storytelling-template-js#21]
When editing the legend to "open by default", it would be great if you could also choose which layers to include in the legend.
I just want the crime layer to display in the legend. The police zones are for background.

![a1c1ff4d-4dd8-4a03-8389-3b412ac250a3](https://cloud.githubusercontent.com/assets/6819070/6102281/67d33f8e-b001-11e4-9d1c-fc4e91a78d82.png)

**Comment by glazou** [comment]
It would be nice to integrate that capability but this is not on our roadmap in the near future because of the complexity of developing such a component from scratch. 
If we could integrate such a control, it's likely we would adopt it.
Workaround is to use Map Viewer.

**Comment by karmstro77** [comment]
Actually, I just realized I can use the 'Hide in Legend' option on the layer in the web map. The Map Journal honors that setting and does not show the layer in the legend.
