### ISSUE TITLE
Allow map actions that reference the same map to occur without resetting the map extent

### ISSUE THREAD

**Issue by bstayeresri** [Esri/map-journal-storytelling-template-js#28]
I want a map action that turns on/off layers in my current map. To do this, I set up a map action that references the same web map with a different content configuration. But when I execute that map action, it always resets my extent to the default full extent of the web map. So if I'm zoomed in somewhere, I can't just turn the layer off and remain where I'm at - I'm forced back out to the full extent.

**Comment by glazou** [comment]
By default, the location get set but if you reset it it should works

**Comment by bstayeresri** [comment]
Thanks, Greg. I just tried it again and it's working as expected. Before, I think I was using a web map through the embed code option rather than directly referencing it.
