### ISSUE TITLE
application does not run without lib-build

### ISSUE THREAD

**Issue by calumbutler** [Esri/map-journal-storytelling-template-js#29]
Trying to create a build, the application is not running without lib-build directory. Grunt will not work because of the changes that we have made to the structure of the code.

**Comment by glazou** [comment]
How can we help?

lib-build is indeed required in development and to create the build version.
If the template is working in development, you should be able to make the grunt task works without too much trouble.

The cons to deploying the development version is that it's slower to load, the difference can be significant especially on mobile device.

**Comment by calumbutler** [comment]
Yeah, the grunt task is causing issues. When we sucesfully create a build, the application fails. 

GET http://www.cmb.com/~calumbutler/workspace/transitDay/2334-apta.TransitDayApp/deploy/app/storymaps/common/mapcontrols/command/MapCommand.js 404 (Not Found)init.js:19 r.getTextinit.js:37 painit.js:15 ainit.js:24 (anonymous function)init.js:33 iainit.js:24 mainit.js:37 Jainit.js:41 Iabuilder-min.js?v=1.2.1:1 (anonymous function)

Is there a way that I should be referencing modules that will point to the correct directory?

currently in MainView.js MapCommand is being referenced as follows         "storymaps/common/mapcontrols/command/MapCommand"

**Comment by glazou** [comment]
You should not have to modify anything. So you don't have any error when running grunt?
Does the file deploy/app/viewer.min.js contain some content?

If you download a fresh version of Map Journal and don't do any modification are you able to build and deploy it?

**Comment by calumbutler** [comment]
Yeah, pulled a clean version of the map journal and it builds a production version fine. The viewer.min,js does have content. The issue i'm having is the references to each file gives me errors in the build. Files are not where the application is looking for them. Does requireJS have issues with nested requires?

**Comment by glazou** [comment]
Nested require won't be picked up during the build.
You have two solutions:
 * add those dependencies to https://github.com/Esri/map-journal-storytelling-template-js/blob/master/src/app/storymaps/tpl/BuildConfigViewer.js so that they are going to be picked up by the build and integrated in viewer-min.js
 * modify the grunt file to also copy those files in the deploy folder (add a copy target https://github.com/Esri/map-journal-storytelling-template-js/blob/master/Gruntfile.js#L152)
