### ISSUE TITLE
Web Server not workin

### ISSUE THREAD

**Issue by LCassagnes** [Esri/map-journal-storytelling-template-js#32]
Hi !

I'm currently trying to install an ArcGis web server with WAMP Server.

I've done all the instructions specified on their github but I can't make this installation work. 

I have add a <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script> to fix some issues I used to have. 

When I try to load the index.html, the logo in the center keep turning and turning without load anything else...

I don't know what can I do to fix this, the google chrome development tool in the "network" session seems ok. All are "GET 200" but some are in "finished" status and I don't know chat that means ?

Can anybody help ?

**Comment by glazou** [comment]
Hi,

Do you have any error in the console? Are you using the user or the developer download?

The most simple to make sure your web server works well, would be that you follow those instructions https://github.com/Esri/map-journal-storytelling-template-js#instructions

You can use the following appid 84c097f098c04c6f8b2b6924ce7f5e1b

**Comment by LCassagnes** [comment]
Hi !

Thanks for your answer !

I've tried what you told me but it didn't work. 
If I download the application from the instructions, I have this error : "	Application loading failed. The application has to be accessed through a web server. Consult user guide for detail." with the warning icon.

And if I download the github repository (.zip) the application keeps loading and loading...

Here is a picture of the application status with development tools from Google Chrome if you want to figure it out : http://hpics.li/19ab5b4

**Comment by glazou** [comment]
Hi,
It is mentioned in the instructions I sent you but I feel I have to ask, have you deployed the application on a webserver? I.e. you are accessing it using http://127.0.0.1?
If you are just clicking on index.html and it launch your browser it will not work.

The instructions contains a link to that section for detail about webserver https://github.com/Esri/map-journal-storytelling-template-js#how-to-deploy-the-application-on-a-web-server

**Comment by LCassagnes** [comment]
My bad, you're right...
I've read the instructions to fast...

Thank you for the help and sorry for the inconvenience !

**Comment by glazou** [comment]
No problem, good luck, I'm closing the issue.
