### ISSUE TITLE
question on hosting map-journal story map

### ISSUE THREAD

**Issue by rwatsondc** [Esri/map-journal-storytelling-template-js#35]
I'm trying to follow the instructions mentioned in previous issues: https://github.com/Esri/map-journal-storytelling-template-js#instructions

After I place the files on a web-server directory and change the appid reference in index.html and load through a web browser the loading bars go in what appears to be an infinite loop (i am accessing through a web server).

Firebug (in firefox) reveals a "scriptError" with some of the following details:
src: dojoLoader
info: ["http://js.arcgis.com/3.1...monConfig.js?v=1.3.0.js", error ]

Additionally - though not sure how else to provide this feedback - regarding the comment about using this application without arcgis online or portal, that functionality would solve a couple implementation problems I have (policy related) and would generally be a helpful feature for any template.

**Comment by rwatsondc** [comment]
please disregard the first part about the instructions not working (seems the server I have is configured oddly)  however I'd still like to communicate the second part

**Comment by glazou** [comment]
Ok cool, glad you solve this. 
Could you provide more detail about the issue the prevent you of using AGOL and Portal? 
You can email me at glazou -a-t- esri -.com- if you want. Thanks
