### ISSUE TITLE
adding edit parameter to enable builder in downloaded template

### ISSUE THREAD

**Issue by mhoole** [Esri/map-journal-storytelling-template-js#36]
"Can I use the builder with the downloadable?

Yes, when the template is configured with an application ID, adding the URL parameter 'edit' will open the builder. You will be prompted for user authentication through the Identity Manager"

Can you explain exactly where and how to add the URL parameter 'edit' - I have tried and failed :(  Thank you!

**Comment by glazou** [comment]
sure, you should be accessing the application using an URL like
`http://localhost/MyJournal/index.html` to use the builder, you have to modify the URL to be `http://localhost/MyJournal/index.html?edit`

Note that except advanced customization or if you have increased the maximum number of sections, you can also just enter the builder through the item in ArcGIS Online. you will not have to know that trick and the changes will apply to both application.

**Comment by mhoole** [comment]
Sweet…thx… I had been trying to append &edit (which works when app is hosted in AGOL) instead of ?edit to the url for app hosted on localhost….
