### ISSUE TITLE
Cannot create a link to https content

### ISSUE THREAD

**Issue by pamrichmond** [Esri/map-journal-storytelling-template-js#42]
When linking text in the sidebar content in the Journal builder, the link dialog removes the "https://" protocol of a secure link immediately. When SSL is required by the target server, clicking the link generates a "403 - Forbidden" error.

![httpslink](https://cloud.githubusercontent.com/assets/4450069/9097123/44614282-3b87-11e5-8967-2482f3835c27.jpg)

Posted this issue at https://geonet.esri.com/thread/163335

**Comment by glazou** [comment]
Thanks for reporting. Will look at fixing this. In the mean time, a simple workaround is to toggle the editor in the HTML source mode and edit the HTML directly.

![image](https://cloud.githubusercontent.com/assets/994078/9176606/1e980988-3f41-11e5-80fa-0be86ad3a02e.png)

**Comment by glazou** [comment]
A fix will be deployed in our upcoming release planned for September 16th.

**Comment by glazou** [comment]
A fixed has been deployed to ArcGIS Online.
