### ISSUE TITLE
Iframe embedding error

### ISSUE THREAD

**Issue by tedrick** [Esri/map-journal-storytelling-template-js#45]
Attempted to embed an iframe from sphershare:

`<iframe src="http://sphereshare.net/#!/e/3dfbc58cc63a4fb9ea7af7fcc13641e9" 
frameborder="0" allowtransparency="true"></iframe>`

Using the web page embed.  Following error was generated:
**Embed code can only contain one &lt;iframe&gt;**

Issue persisted after I switched to an &lt;iframe /&gt; format

**Comment by glazou** [comment]
Sorry about the issue, the dialog don't like any extra white space or line return before or after the iframe . If you make sure to have none embedding should works.
