### ISSUE TITLE
Facebook/twitter links for pages in mobile view?

### ISSUE THREAD

**Issue by upcamogie** [Esri/map-journal-storytelling-template-js#49]
My app has the Facebook and Twitter links on each page of my journal, but they are not available in the mobile view. Is this a limitation, bug, or user error on my part? I have a request to be able to share individual pages as they each point to unique projects. I'd also like to have the links have my URL and not the AGOL map-- the main FB and Twitter link on the home page uses my URL but the individual pages do not. thanks.

**Comment by glazou** [comment]
The issue about the sharing links not using the proper URL is on my list of issue to fix for next release. 

I will also include in next release the social media links on each page of the mobile view, seems like we forgot to do that (that feature is not very popular).

The release is planned for February 28th, thanks for your feedback.
