### ISSUE TITLE
navigation links as buttons instead of text?

### ISSUE THREAD

**Issue by upcamogie** [Esri/map-journal-storytelling-template-js#50]
I could have sworn I saw somewhere to add the ability of navigation explained here 

[https://github.com/Esri/map-journal-storytelling-template-js#link-between-sections]
 
with buttons instead of just text, but I cannot seem find that code sample anywhere. Am I dreaming this or is this possible? Maybe it was on another story maps template, but regardless I'd like to have a buttons instead text is possible. Posted on Geonet too but so far no response. thanks for any leads

**Comment by ccrozek** [comment]
do you mean like this? I saved a bookmark for where I learned how to do it, but the website isn't working right now. You can see the article here, but not get to it: https://medium.com/@OwenGeo. It was from using custom CSS, so if the website doesn't come back up, I could look at what code I have behind it for you.
![image](https://cloud.githubusercontent.com/assets/10961053/12682183/2a656bae-c680-11e5-8fca-5a0b66162ec4.png)

**Comment by upcamogie** [comment]
yes, I think that is the same link I saw. I will reach out to the author as I know him and hopefully I can get that example back. Otherwise, I may reply back here to ask you to look through your files. Thanks!

**Comment by oevans** [comment]
Sorry the developers' corner is down right now do to some issues implementing a new custom URL. Here's a copy of that post as a PDF.

[Editing Create Buttons for Main Stage Actions in Map Journal.pdf](https://github.com/Esri/map-journal-storytelling-template-js/files/110154/Editing.Create.Buttons.for.Main.Stage.Actions.in.Map.Journal.pdf)
