### ISSUE TITLE
popup text color changes when using formatted HTML on side panel

### ISSUE THREAD

**Issue by upcamogie** [Esri/map-journal-storytelling-template-js#53]
I am finding this out the hard way...my popups appear to be blank but I've discovered the text is there but now white, so you cannot see it against the background of the popup window. It does not seem to matter where this HTML is (on what page)-- it affects the entire application, including the builder dialogs (I am using the downloaded template  (using appid) & still configuring my app via AGOL builder)

I have a need to have formatted (with styles) in my side panel and this seems to have caused the issue.

Is this a bug? Besides taking out alll of my styles, is there any way to fix this and/or only have the changes I need per page and not the entire app?

**Comment by glazou** [comment]
It seems that your custom style is causing the issue. If you are doing something like `body { color: #FFF; }` to set the color to white yes that would cause most of the application to go white. You want to use a more specific selector like `.section { color: #FFF; }`.

Do you know that there is a color tool in the text editor? You can use it to style all the text that appear in the side panel

**Comment by upcamogie** [comment]
yes, I am using the color tool in the editor-- had to do that to change some things that were not applying correctly via the HTML. Trouble is I am incorporating HTML from someone else who formatted it so I am trying to find the issue causing this. the css issue makes sense, have to look more closely at it and try to pass on specs to the HTML person. thx for quick response
