### ISSUE TITLE
Twitter sharing dialog include line break before app link

### ISSUE THREAD

**Issue by glazou** [Esri/map-journal-storytelling-template-js#58]
Described in https://github.com/Esri/map-journal-storytelling-template-js/issues/51#issuecomment-193367114. This seems to happen after the home section is edited (even if no modification is made to the title).

![image](https://cloud.githubusercontent.com/assets/9007801/13577851/a52cd368-e462-11e5-8f62-a4df4fbbc089.png)

This cannot be fixed from the builder, there is a workaround that you can use at your own risk. The title can be edited through the following application: https://ago-assistant.esri.com/ This lets you edit the story associated JSON in your ArcGIS Online account, when performing edits you have to be careful to not make invalid edit that could compromise the item. You may not be able to recover your item if you make a JSON syntax error. If you find your Journal, use "I want to > View an item JSON" content and scroll down you will see the title property that is used on Twitter and include a trailing `\n`, enter in edit mode, save it, reload the application and it should be fixed.

![image](https://cloud.githubusercontent.com/assets/994078/13579318/b6d68a5c-e451-11e5-83f3-82763a122abb.png)

**Comment by upcamogie** [comment]
Thanks- I will use AGO assistant (that is how I changed my title initially anyway)

**Comment by glazou** [comment]
I have been able to fix this issue in ArcGIS Online last night, and just released the corresponding update on GitHub: V1.7.1.
