### ISSUE TITLE
Layers from web not displaying

### ISSUE THREAD

**Issue by pleavin** [Esri/map-journal-storytelling-template-js#63]
In several instances I've added "layers from the web" (.csv files) to my map. They show up on the arcgis site in the preview. However on my localhost and where I am hosting the demo of my storymap they do not show up. When I use the same file under the add "layers from file" option they do display.

**Comment by glazou** [comment]
When your story is hosted in ArcGIS Online, it will use a proxy to access the CSV as this is required by some browser.

When you host the application yourself, the proxy is not be available and you need to install your own if you want to use CSV hosted on the web. Please see the following documentation to install a proxy on your computer and then configure it in `apps/config.js` through this line https://github.com/Esri/map-journal-storytelling-template-js/blob/master/src/app/config.js#L161
