### ISSUE TITLE
Specific sequence of characters in title breaks browser

### ISSUE THREAD

**Issue by bpoteat** [Esri/map-journal-storytelling-template-js#68]
If you enter something like:
`This is a "test". It fails >99% of the time.`
as the title of a section in a story, it will lock up that tab of the browser, requiring that the process for that tab be killed.

Remove the `>` and it works. Remove the quotes around "test" and it works.

**Comment by glazou** [comment]
Sorry about that, thanks for reporting. Will fix that for our next release.
