### ISSUE TITLE
Progress to next section in 'Main Stage Actions'

### ISSUE THREAD

**Issue by brianjbaldwin** [Esri/map-journal-storytelling-template-js#7]
A great enhancement would be the ability to progress to the next section using the Main Stage Actions pane.  Could then use an image, text, or icon to trigger the transition.

**Comment by glazou** [comment]
The following article describe how a link can the side panel can navigate to another section https://developerscorner.storymaps.arcgis.com/adding-links-to-sections-in-story-map-journal-a875bb45fdd5#.gbtmnmp4l This can be done without any customization. We also have the following documentation that describe how to implement map driven navigation and require hosting of the application https://github.com/Esri/map-journal-storytelling-template-js#link-between-sections
