### ISSUE TITLE
Popup Configuration not saving with main stage action for side panel

### ISSUE THREAD

**Issue by brianjbaldwin** [Esri/map-journal-storytelling-template-js#8]
The one action that isnt working is getting a popup to be active with a stage action. Map will add a layer, but the popup will not appear.

**Comment by upcamogie** [comment]
I now have a very similar issues-- my popups are appearing when a feature is clicked, but I cannot use the customization to show the popups open by default- make the change, save but then nothing. Did not appear to have a problem until today, an hour before this is supposed to go live!
